services:
  db:
    image: postgres:16.1
    container_name: explorewithme
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  stats-server:
    build:
      context: stats/server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SERVER_ADDRESS=0.0.0.0
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: sh -c "sleep 10 && java -jar app.jar"

  ewm-service:
    restart: on-failure
    build: ./main
    image: ewm-main-service
    container_name: "ewm-main-service"
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://explorewithme:9090