services:
  ewm-service:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        JAR_FILE: server/target/*.jar
    container_name: java-explore-with-me_server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
      args:
        JAR_FILE: gateway/target/*.jar
    container_name: java-explore-with-me_gateway
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service
    environment:
      - STATS_SERVER_URL=http://ewm-service:9090

  db:
    image: postgres:16.1
    container_name: java-explore-with-me_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10